---
apiVersion: v1
kind: Namespace
metadata:
  name: users-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: users-api-ingress
  namespace: users-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-dns-prod"
    certmanager.k8s.io/acme-dns01-provider: "cloud-dns"

spec:
  tls:
  - hosts:
    - users.datasets.pr.mysticjump.com
    secretName: users-api-tls
  rules:
  - host: users.datasets.pr.mysticjump.com
    http:
      paths:
      - path: /
        backend:
          serviceName: users-api
          servicePort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: users-api
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: users-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-api
  namespace: users-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api
        environment: dev
    spec:
      volumes:
      - name: service-account
        secret:
          secretName: service-account
      - name: nginx-ssl
        secret:
          secretName: users-api-tls
      - name: esp-config
        configMap:
          name: esp-config

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100

        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - users-api
              - key: environment
                operator: In
                values:
                - dev

      containers:
      - name: esp
        # TODO: Resource requests
        image: gcr.io/endpoints-release/endpoints-runtime:1
        command: ["/bin/bash"]
        args: [
          "/esp-config/startup.sh"
        ]
        workingDir: /home
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   timeoutSeconds: 1
        #   successThreshold: 1
        #   failureThreshold: 10
        ports:
          - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl_ro
          name: nginx-ssl
          readOnly: true
        - mountPath: /esp-config
          name: esp-config
          readOnly: true

      - name: grpc-server
        # TODO: Resource requests
        imagePullPolicy: Always
        image: gcr.io/analyticsframework/datasets/apis/users/grpc-server:0.2.3-alpha
        args: [
          "--port=8081",
        ]
        ports:
          - containerPort: 8081
        volumeMounts:
        - mountPath: /home/service-account/
          name: service-account
          readOnly: true
        env:
            # TODO: Auto-generate / load from secrets
            #       This is used as the secret to sign pagination tokens.
          - name: API_SECRET
            value: d3a3a9fa-e9a6-11e8-8f08-cbc7b94bc33d
          - name: API_DATASTORE_PROJECT
            value: analyticsframework
          - name: API_DATASTORE_NAMESPACE
            value: datasets-users-api
          - name: API_GSUITE_AUTH_SUBJECT
            value: svc_srce_admin@magicleap.com
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /home/service-account/service-account.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esp-config
  namespace: users-api
data:
  startup.sh: |
    mkdir -p /etc/nginx/ssl/
    cp /etc/nginx/ssl_ro/tls.crt /etc/nginx/ssl/nginx.crt
    cp /etc/nginx/ssl_ro/tls.key /etc/nginx/ssl/nginx.key

    echo "Starting ESP"

    /usr/sbin/start_esp \
      --ssl_port=443 \
      --service=users.endpoints.analyticsframework.cloud.goog \
      --rollout_strategy=managed \
      --backend=grpc://127.0.0.1:8081 \
      --cors_preset=basic \
      --cors_allow_origin=* \
      --cors_allow_methods=GET,POST,OPTIONS,PUT,DELETE,PATCH \
      --cors_allow_headers=Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,x-api-key,x-grpc-web \
      --cors_allow_credentials
