---
#apiVersion: networking.k8s.io/v1beta1  # TODO: use this for Kubernetes 1.16
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app_name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
    certmanager.k8s.io/acme-dns01-provider: "cloud-dns"

spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.app_name }}-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app_name }}
          servicePort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: {{ .Values.app_name }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app_name }}
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 30  # TODO: Add a custom metric to scale based on requests
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
    environment: dev
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
      environment: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
        environment: dev
    spec:
      volumes:
      - name: datasets-users-api-service-account
        secret:
          defaultMode: 420
          secretName: datasets-users-api-service-account
      - name: nginx-ssl
        secret:
          defaultMode: 420
          secretName: {{ .Values.app_name }}-tls
      - name: esp-config
        configMap:
          defaultMode: 420
          name: esp-config

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100

        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.app_name }}
              - key: environment
                operator: In
                values:
                - dev

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      containers:
      - name: esp
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        image: gcr.io/endpoints-release/endpoints-runtime:1
        command: ["/bin/bash"]
        args: [
          "/home/startup.sh"
        ]
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "900m"
        ports:
          - containerPort: 443
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/ssl_ro
          name: nginx-ssl
          readOnly: true
        - mountPath: /home
          name: esp-config
          readOnly: true

      - name: grpc-server
        imagePullPolicy: Always
        image: gcr.io/ml-datasets-pr/apis/users/grpc-server:{{ .Values.grpc_image_tag }}
        args: [
          "--port=8081",
        ]
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "900m"
        ports:
          - containerPort: 8081
            protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/service-account/
          name: datasets-users-api-service-account
          readOnly: true
        env:
          - name: API_SECRET
            value: {{ .Values.api_secret }}
          - name: API_DATASTORE_PROJECT
            value: {{ .Values.api_datastore_project }}
          - name: API_DATASTORE_NAMESPACE
            value: datasets-users-api
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /home/service-account/service-account.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esp-config
  namespace: {{ .Values.namespace }}
data:
  startup.sh: |
    mkdir -p /etc/nginx/ssl/
    cp /etc/nginx/ssl_ro/tls.crt /etc/nginx/ssl/nginx.crt
    cp /etc/nginx/ssl_ro/tls.key /etc/nginx/ssl/nginx.key

    echo "Starting ESP"

    /usr/sbin/start_esp \
      --ssl_port=443 \
      --pid_file=/tmp/nginx.pid \
      --service={{ .Values.domain }} \
      --rollout_strategy=managed \
      --backend=grpc://127.0.0.1:8081 \
      --cors_preset=basic \
      --cors_allow_origin=* \
      --cors_allow_methods=GET,POST,OPTIONS,PUT,DELETE,PATCH \
      --cors_allow_headers=Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,x-api-key,x-grpc-web \
      --cors_allow_credentials \
      --healthz=healthz
